# Darkmode JS
# For more information: https://github.com/rqh656418510/hexo-next-darkmode, https://github.com/sandoche/Darkmode.js
darkmode_js:
  enable: true
  bottom: '64px' # default: '32px'
  right: 'unset' # default: '32px'
  left: '30px' # default: 'unset'
  time: '0.5s' # default: '0.3s'
  mixColor: 'transparent' # default: '#fff'
  backgroundColor: 'transparent'  # default: '#fff'
  buttonColorDark: '#222' # default: '#222'
  buttonColorLight: '#222' # default: '#222'
  isActivated: false # default false
  saveInCookies: true # default: truhexo 
  label: '' # default: '🌓'
  icon: 'fas fa-circle-half-stroke' #default 'fas fa-circle-half-stroke'
  autoMatchOsTheme: true # default: true
